spring:
  datasource:
    primary:
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    replica:
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

  jpa:
    show-sql: false

  sql:
    init:
      mode: never

datasource-init:
  schema-location: classpath:schema.sql
  data-location: classpath:test-data.sql

# Embedded Redis for test
redis:
  embedded:
    enabled: true
    port: 6371

logging:
  level:
    com.musinsa: INFO
