spring:
  jpa:
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

# Embedded Redis
redis:
  embedded:
    enabled: true
    port: 6370

logging:
  level:
    com.musinsa: DEBUG
    org.springframework.transaction: DEBUG
